name: Go Project CI

concurrency:
  group: ci-workflow-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - "*"

env:
  SERVICE: go-project-template

jobs:
  lint:
    name: Run golangci-lint
    runs-on: [ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          args: --config=.golangci.yml

  test:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.x"
      - name: Run test
        run: go test -race -v ./...
